### ISSUE TITLE
mmal: mmal_component_create_core: could not find component 'vc.ril.camera'

### ISSUE THREAD

**Issue by mich04** [jacksonliam/mjpg-streamer#117]
Hi I am running Arch Linux, I have been using mjpeg-streamer for about a year now. I recently switched over to your fork. When I try to use input_raspicam.so this is what happens 
sudo mjpg_streamer -o "/usr/lib/mjpg-streamer/output_http.so -w ./www" -i "/usr/lib/mjpg-streamer/input_raspicam.so"

nent_create_core: could not find component 'vc.ril.camera'

My device is a raspberry pi zero w with a 5mp csi camera which is access at /dev/video0 raspistll and raspivid both work as well as mjpg_streamer when I use 

ExecStart=/usr/bin/mjpg_streamer --i "/usr/lib/mjpg-streamer/input_uvc.so -d /dev/video0 -r 1280x960 -f 30" -o "/usr/lib/mjpg-streamer/output_http.so -p 8090 -w /tmp"

**Comment by jacksonliam** [comment]
I can only think that either something is different on arch, perhaps something missing, (and raspivid and v4l2 work because they are included in the distribution) because I don't see this issue on raspbian.

Did you do anything to enable the v4l2 driver? I wonder if it's using the camera so raspivid can't open it? 

If you figure out what needs to be done to get this working, please let me know!

I don't think there's a problem using the input_uvc plugin if that's working for you.
