### ISSUE TITLE
Grey pixel picture if started via SSH

### ISSUE THREAD

**Issue by Trolli91** [jacksonliam/mjpg-streamer#279]
Hello at all,

first of all I want to mention that mjpg-streamer in general is working great for me. If I am logged in on the desktop and start the program than I get 2 streams with a high framerate which perfectly match my needs.
However when I am sending the command via SSH to my Raspberry to start mjpg-streamer than the software is starting, however the picture is not really working for me:
![Unbenannt2](https://user-images.githubusercontent.com/74912275/99964947-6a7e3d80-2d94-11eb-9353-9c945831445a.PNG)

It changes between this type of picture and a complete greyed out picture. I can see some objects which can be identified, so the camera in general seems to work. Are there any ideas what could be the issue? As mentioned if I do it in a console it's working perfectly, just when I send the SSH command remotely. Here is my startup command:

`/usr/local/bin/mjpg_streamer -i "/usr/local/lib/mjpg-streamer/input_uvc.so -n -f 30 -d /dev/video0 -r 1280x720" -i "/usr/local/lib/mjpg-streamer/input_uvc.so -n -f 30 -d /dev/video2 -r 1280x720" -o "/usr/local/lib/mjpg-streamer/output_http.so -p 8081 -w /usr/local/share/mjpg-streamer/www"`

**Comment by jacksonliam** [comment]
I cannot see how there would be anything mjpg-streamer is doing differently in that case. I think it must be some hardware/environment/system problem.
Are you sure the two setups (doing it via console vs via. SSH) are otherwise identical? There is no difference in terms of power supply, usb hubs, networking, etc?

E.g. can you type the command in the console (while also having an SSH session open) and view it fine, cancel it in the console and then run it via SSH immediately after and see the picture issue?
